[package]
name = "v8_worker_snapshot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deno_core = { version = "0.129" }

anyhow = { version = "1", optional = true }
deno_broadcast_channel = { version = "0.41", optional = true }
deno_console = { version = "0.47", optional = true }
deno_crypto = { version = "0.61", optional = true }
deno_fetch = { version = "0.70", optional = true }
deno_ffi = { version = "0.34.0", optional = true }
deno_http = { version = "0.41",  optional = true }
deno_net = { version = "0.39", optional = true }
deno_tls = { version = "0.34", optional = true }
deno_url = { version = "0.47", optional = true }
deno_web = { version = "0.78", optional = true }
deno_webgpu = { version = "0.48.0", optional = true }
deno_webidl = { version = "0.47", optional = true }
deno_websocket = { version = "0.52", optional = true }
deno_webstorage = { version = "0.42", optional = true }
glob = { version = "0.3", optional = true }
zstd = "0.11"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.11"
winapi = "0.3.9"

[features]
build = ["anyhow", "deno_broadcast_channel", "deno_console", "deno_crypto", "deno_fetch", "deno_ffi", "deno_http", "deno_net", "deno_tls", "deno_url", "deno_web", "deno_webgpu", "deno_webidl", "deno_websocket", "deno_webstorage", "glob"]
