[package]
name = "deno-utils"
version = "0.1.0"
edition = "2021"
license = "MIT"
documentation = "https://docs.rs/deno-utils"
repository = "https://github.com/tyrchen/deno-utils"
homepage = "https://github.com/tyrchen/deno-utils"
description = """
Utility functions for deno.
"""
readme = "README.md"
keywords = ["loader", "deno", "v8"]
categories = ["development-tools"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data-url = "0.1.1"
deno_core = "0.129"
deno_graph = "0.26"
futures = "0.3"
pin-project = "1"
reqwest = "0.11"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "fs"] }

deno-transpiler = { version = "0.1", path = "../transpiler" }
