[package]
name = "deno-utils"
version = "0.2.4"
edition = "2021"
license = "MIT"
documentation = "https://docs.rs/deno-utils"
repository = "https://github.com/tyrchen/deno-utils"
homepage = "https://github.com/tyrchen/deno-utils"
description = """
Utility functions for deno.
"""
readme = "README.md"
keywords = ["loader", "deno", "v8"]
categories = ["development-tools"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.53"
data-url = "0.1.1"
deno_core = "0.132.0"
deno_graph = "0.26.0"
dirs = "4.0.0"
futures = "0.3.21"
pin-project = "1.0.10"
reqwest = "0.11.10"
tokio = { version = "1.18.1", features = ["rt", "rt-multi-thread", "fs"] }

deno-transpiler = { version = "0.2.2", path = "../transpiler" }
