[package]
name = "deno-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data-url = "0.1.1"
deno_core = "0.129"
deno_graph = "0.26"
futures = "0.3"
hyper = "0.14"
pin-project = "1"
reqwest = "0.11"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "fs"] }

deno-transpiler = { path = "../transpiler" }
